export const siteConfig = {
  brand: "Trust Contractors Inc",
  officialName: "Trust Contractors Inc",
  domain: "https://www.trustcontractorsboston.com",
  legacyWebsiteUrl: "https://www.trustcontractorsboston.com",
  legacyServicesUrl: "https://www.trustcontractorsboston.com/construction-services",
  legacyGalleryUrl: "https://www.trustcontractorsboston.com/gallery#ConstructionServices",
  googleBusinessProfile: "https://share.google/gdKWQ8iR7VA9mPS4s",
  ownerName: "Jean Oliveira",
  primaryPhoneDisplay: "(781) 277-8381",
  primaryPhoneRaw: "7812778381",
  businessPhoneDisplay: "(781) 277-8381",
  businessPhoneRaw: "7812778381",
  email: "trustcontractorsinc@gmail.com",
  commercialEmail: "trustcontractorsinc@gmail.com",
  foundedYear: 2003,
  yearsInBusiness: "Over 20 years",
  employeeCount: 3,
  serviceRadiusMiles: 20,
  minimumJobSize: "$30K",
  idealJobSize: "$175K additions and remodeling",
  serviceHours: {
    weekdays: "Mon - Sun: 6:30 AM - 7:30 PM",
    estimates: "Estimate appointments available anytime",
    estimateTurnaround: "Estimates typically completed within 3 days",
  },
  offers: {
    estimate: "Free in-person estimates",
  },
  seo: {
    defaultDescription:
      "Trust Contractors Inc provides new construction, additions, remodeling, roofing, carpentry, siding, painting, and general contracting across Greater Boston.",
  },
  widgets: {
    chatWidgetId: "6a4e7192f505ece9b449bc56",
    chatLoaderSrc: "https://widgets.leadconnectorhq.com/loader.js",
    chatResourcesUrl: "https://widgets.leadconnectorhq.com/chat-widget/loader.js",
  },
  gohighlevel: {
    locationId: "5HX3873p6HhdUSTpBxAl",
    trackingId: "tk_5d6ee6ddd46c44babae8fdf1a2ed25ef",
    externalTrackingScriptSrc: "https://link.adssurveys.com/js/external-tracking.js",
    quoteFormId: "Free Estimate Form",
    inlineFormId: "3G6eLO14xFk14EUSDju4",
    inlineFormUrl: "https://link.adssurveys.com/widget/form/3G6eLO14xFk14EUSDju4",
    inlineFormEmbedScriptSrc: "https://link.adssurveys.com/js/form_embed.js",
  },
  reputationHub: {
    reviewWidgetScriptSrc: "https://reputationhub.site/reputation/assets/review-widget.js",
    reviewWidgetIframeSrc: "https://reputationhub.site/reputation/widgets/review_widget/5HX3873p6HhdUSTpBxAl",
  },
  assets: {
    logo: "/trust-contractors-logo.png",
    favicon: "/favicon.svg",
    ogImage: "/og-image.png",
    homeHeroImage: "/home-hero-banner.jpeg",
    heroImage: "/hero.jpg",
    aboutHeroImage: "/hero.jpg",
  },
};
