export const siteConfig = {
  brand: "Fixon Construction",
  officialName: "Fixon Construction",
  domain: "https://adstructdigital.com",
  legacyWebsiteUrl: "https://adstructdigital.com",
  ownerName: "Ronnie Costa",
  ownerTitle: "CEO",
  primaryPhoneDisplay: "(475) 316-8500",
  primaryPhoneRaw: "14753168500",
  businessPhoneDisplay: "(475) 316-8500",
  businessPhoneRaw: "14753168500",
  email: "costapaintingllc@gmail.com",
  commercialEmail: "costapaintingllc@gmail.com",
  foundedYear: 2016,
  yearsInBusiness: "10 years",
  employeeCount: 4,
  serviceRadiusMiles: 50,
  minimumJobSize: "$1,000",
  idealJobSize: "$10,000+",
  businessType: "LLC",
  serviceHours: {
    weekdays: "Mon–Sat: Estimate windows 10 AM–2 PM & 4–6 PM",
    estimates: "In-person estimates by appointment",
    estimateTurnaround: "Estimates typically completed by the next business day",
  },
  offers: {
    estimate: "Free in-person estimates",
  },
  seo: {
    defaultDescription:
      "Fixon Construction provides roofing, kitchen and bathroom remodeling, basement finishing, renovations, and general contracting across Hartford, CT and surrounding areas.",
  },
  widgets: {
    chatWidgetId: "6a6358626890ba7f8449f6cc",
    chatLoaderSrc: "https://widgets.leadconnectorhq.com/loader.js",
    chatResourcesUrl: "https://widgets.leadconnectorhq.com/chat-widget/loader.js",
  },
  gohighlevel: {
    locationId: "",
    trackingId: "",
    externalTrackingScriptSrc: "https://link.adssurveys.com/js/external-tracking.js",
    quoteFormId: "Main Form",
    inlineFormId: "iQ6pW9D35SMd10wBYXVL",
    inlineFormUrl: "https://link.adssurveys.com/widget/form/iQ6pW9D35SMd10wBYXVL",
    inlineFormEmbedScriptSrc: "https://link.adssurveys.com/js/form_embed.js",
    bookingWidgetId: "aMPTz0I8dGQxPSSk6hh0",
    bookingWidgetUrl: "https://link.adssurveys.com/widget/booking/aMPTz0I8dGQxPSSk6hh0",
    bookingWidgetIframeId: "aMPTz0I8dGQxPSSk6hh0_1784898602016",
  },
  reputationHub: {
    reviewWidgetScriptSrc: "",
    reviewWidgetIframeSrc: "",
  },
  googleBusinessProfile: "",
  assets: {
    logo: "/fixon-construction-logo.png",
    favicon: "/favicon.png",
    ogImage: "/home-hero-banner.jpeg",
    homeHeroImage: "/home-hero-banner.jpeg",
    heroImage: "/home-hero-banner.jpeg",
    aboutHeroImage: "/gallery/preview/cs-16.jpeg",
  },
};
